apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-3kbc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-3kbc
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-3kbc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-3kbc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-3kbc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xsdv-tenant/rhtap-demo-app/hacbs-test-project-3kbc@sha256:c69eb48c940b12951d328e4317438d1437bfa09a2ac3aa75f1ebcf48cba62025
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
