apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-3kbc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xsdv-tenant/rhtap-demo-app/hacbs-test-project-3kbc@sha256:3ad75bf67bf028f64271e1e8bad3440906b63e312168b0d7b0b443a55b31b171
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
